include:
  #- project: 'dhei/teams/io/templates/gitlab-pipelines'
  #  file: '/docker/gitlab-ci.docker.yml'
  #  ref: develop
  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  MTR_TARGET_IMAGE:   eni-kong
  MTR_TARGET_TAG:     ${CI_COMMIT_REF_NAME}-test
  TAG_SED_REGEX:      's,^.*/,,'

stages:
- test
- dockerize
- publish

default:
  tags: [ "otc_run_docker_m" ]

# jobs

semgrep:
  image: returntocorp/semgrep
  stage: test
  script: semgrep ci --gitlab-sast > gl-sast-report.json || true
  rules:
  - changes:
      - .gitlab-ci.yml
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: $CI_MERGE_REQUEST_IID
  - if: $CI_PIPELINE_SOURCE == "push"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_COMMIT_BRANCH == "develop"
  
  variables:
    SEMGREP_RULES: >-
      p/security-audit
      p/secrets
      p/default
      p/ci
      p/docker
    SEMGREP_GITLAB_JSON: "1"
  artifacts:
    reports:
      sast: gl-sast-report.json

#build:image:
#  when: manual
#  extends: .docker:build:mtr-devops-internal-with-tardis-common-and-dependencies
#  stage: dockerize

build:image:
  when: manual
  image:
    name: artifactory.devops.telekom.de/gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: [ "" ]
  tags: [ "otc_run_docker_k8s_m" ]
  stage: dockerize
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${MTR_DEVOPS_REGISTRY}/tardis-internal\":{\"username\":\"${MTR_DEVOPS_TARDIS_INTERNAL_PUSH_USER}\",\"password\":\"${MTR_DEVOPS_TARDIS_INTERNAL_PUSH_TOKEN}\"},\"${MTR_DEVOPS_REGISTRY}/tardis-common\":{\"username\":\"${MTR_DEVOPS_TARDIS_COMMON_PULL_USER}\",\"password\":\"${MTR_DEVOPS_TARDIS_COMMON_PULL_TOKEN}\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --registry-mirror dockerhub.devops.telekom.de
      --context ./
      --dockerfile ./Dockerfile
      --destination ${MTR_DEVOPS_REGISTRY}/${MTR_DEVOPS_GROUP_INTERNAL}/${MTR_TARGET_IMAGE}:$(echo "${MTR_TARGET_TAG}" | sed -r 's/[/]/-/g')
      --cache=true --cache-repo ${MTR_DEVOPS_REGISTRY}/${MTR_DEVOPS_GROUP_INTERNAL}/${MTR_TARGET_IMAGE}:$(echo "${MTR_TARGET_TAG}" | sed -r 's/[/]/-/g')
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg no_proxy=$no_proxy
